{% set name = "sparrow" %}
{% set pkg_name = "scine-" + name %}
{% set version = "3.1.0" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/sparrow/archive/refs/tags/{{ version }}.tar.gz
    sha256: 91412de0f2670a1735c4ca76406db5bea04236eeac0bc1f93ccfe18104aa7ce4
    fn: {{ name }}.tar.gz
    patches:
      - osx_tests.patch  # [osx]
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.0.tar.gz
    sha256: bb2f161ed15811def85ca635924427356564a811779993123077f4ada048be84
    fn: dev.tar.gz
    folder: dev

build:
  number: 1
  skip: true  # [win]
  script:
    - set -ex
    - >
      cmake ${CMAKE_ARGS} -B _build -G Ninja -DSCINE_MARCH=""
    - cmake --build _build
    - ctest --test-dir _build --output-on-failure -R '^Sparrow$'  # [build_platform == target_platform]
    - cmake --install _build

  run_exports:
    - {{ pin_subpackage(pkg_name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - boost-cpp
    - cereal
    - eigen
    - gtest
    - gmock
    - libblas
    - scine-core
    - scine-utilsos
  run:
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/bin/{{ name }}
    - {{ name }} --help  # [build_platform == target_platform]


about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Sparrow is a code for fast semiempirical quantum chemical calculations
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/sparrow

extra:
  recipe-maintainers:
    - awvwgk
